use_frameworks!

target 'FFCategory_Example' do
  pod 'FFCategory', :path => '../'

  target 'FFCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
